version: "3"

services:
  postgres:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: wf-demo
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
  redisdata:
